cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

processors: ${PROCESSORS:1}

network.host: ${NETWORK_HOST:0.0.0.0}

path:
  data: ${PATH_DATA:/data/data}
  logs: /data/log

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

xpack.ml.enabled: false

transport.tcp.port: ${TRANSPORT_PORT}
http.port: ${HTTP_PORT}

indices:
  memory:
    index_buffer_size: ${INDEX_BUFFER_SIZE}

thread_pool:
  index:
    queue_size: ${INDEX_QUEUE_SIZE}

# disable disk allocation
cluster:
  routing:
    allocation:
      disk:
        threshold_enabled: ${ALLOW_DISK_ALLOCATION}
        watermark:
          # this is the threshold to move shard to other node
          # (which we don't have in single node mode so put it to 100%)
          high : ${DISK_WATERMARK_HIGHT}
          #threshold for read only lock
          flood_stage: ${DISK_WATERMARK_FLOOD_STAGE}
      #for single node only allow only primary shard. We don't need replica
      enable: ${SHARD_REBALANCING_FOR}